SELECT TOP (1000) [VehicleTemperatureID]
      ,[VehicleRegistration]
      ,[ChillerSensorNumber]
      ,[RecordedWhen]
      ,[Temperature]
      ,[FullSensorData]
  FROM [WideWorldImporters].[Website].[VehicleTemperatures]